In [8]:
pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.6 MB 2.2 MB/s eta 0:00:06
   --- ------------------------------------ 1.0/12.6 MB 2.7 MB/s eta 0:00:05
   ---- ----------------------------------- 1.3/12.6 MB 2.3 MB/s eta 0:00:05
   ----- ---------------------------------- 1.8/12.6 MB 2.2 MB/s eta 0:00:05
   ------- -------------------------------- 2.4/12.6 MB 2.1 MB/s eta 0:00:05
   -------- ------------------------------- 2.6/12.6 MB 2.0 MB/s eta 0:00:05
   ---------- ----------------------------- 3.1/12.6 MB 2.0 MB/s eta 0:00:05
   ----------- ---------------------------- 3.7/12.6 MB 2.1 MB/s eta 0:00:05
   ------------ --------------------------- 3.9/12.6 MB 2.1 MB/s eta 0:00:05
   -------------- ------------------------- 4.5/12.6 MB 2.1 MB/s eta 0:00:04
   --------------- ------------------------ 5.0/12.6 MB 2.0 MB/s eta 0:00:04
   ----------

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [9]:
import numpy as np

In [11]:
a = []
size = int(input("Enter size:"))
for i in range(size):
    val = int(input("Enter  number: "))
    a. append(val)
print (a)
b = np. array(a)
b

[1, 2, 3]


array([1, 2, 3])

In [12]:
a = [[1,2,3],[3,4,5],[6,7,8]]
b = np.array(a)
b

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
import numpy as np 
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [14]:
b=np.ones((2,4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
b = np.eye(3,3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
import numpy as np 
a = np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [33]:
import numpy as np 
a = np. random.randint(1,57,3)
a






array([50, 23, 22], dtype=int32)

In [34]:
a = np. random.rand(5)
a

array([0.12707988, 0.67788472, 0.10168779, 0.25257785, 0.33189768])

In [35]:
a = np. random.randn(5)
a

array([-0.17077913, -1.97179341,  0.99611268, -0.50240092, -0.11338463])

In [39]:
a = np. random.randint(5,34,12)
a

array([17, 18, 27, 14, 15, 25, 14, 26, 28, 30, 28, 19], dtype=int32)

In [42]:
a.shape

(12,)

In [44]:
a.reshape(2,6)


array([[17, 18, 27, 14, 15, 25],
       [14, 26, 28, 30, 28, 19]], dtype=int32)

In [45]:
a.reshape(3,4)


array([[17, 18, 27, 14],
       [15, 25, 14, 26],
       [28, 30, 28, 19]], dtype=int32)

In [47]:
np.random.seed(50)
a = np.random.randint(1,100,10) 
a

array([49, 97, 12, 34, 95,  5, 71, 71, 23,  6], dtype=int32)

In [48]:
a=np.array([10,20,30,40,50,60,70,80,])
b=a[3:6]
b[:]=0
a

array([10, 20, 30,  0,  0,  0, 70, 80])

In [49]:
a=np.array([10,20,30,40,50,60,70,80,])
b=a[3:6].copy()
b[:]=0
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [50]:
b

array([0, 0, 0])

In [51]:
a=np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
a>=10


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False])

In [54]:
a<10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False])

In [58]:
b=a>10
a[b]

array([11, 12, 13, 14, 15])

In [ ]:
a[a%2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [62]:
a=np.array([5,6,7,8]).reshape(2,2)
a

array([[5, 6],
       [7, 8]])

In [66]:
b=np.array([1,2,3,4]).reshape(2,2)
b

array([[1, 2],
       [3, 4]])

In [67]:
a + b

array([[2, 4],
       [6, 8]])

In [68]:
a-b

array([[0, 0],
       [0, 0]])

In [69]:
b-a

array([[0, 0],
       [0, 0]])

In [70]:
a*b

array([[ 1,  4],
       [ 9, 16]])

In [71]:
a/b

array([[1., 1.],
       [1., 1.]])

In [81]:
a=np.array([1,20,30,40,5,0,60])
np.unique(a , return_index  = True, return_counts =  True)

(array([ 0,  1,  5, 20, 30, 40, 60]),
 array([5, 0, 4, 1, 2, 3, 6]),
 array([1, 1, 1, 1, 1, 1, 1]))

In [4]:
# Q1.
import numpy as np

In [5]:
# Q2.
a = [1,2,3,4,5]
print(np.array(a))

[1 2 3 4 5]


In [6]:
# Q3
a = np.random.randint(1,10,10)
a

array([4, 8, 6, 6, 9, 2, 8, 4, 6, 1], dtype=int32)

In [7]:
# Q4
a = np.arange(10,21)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [8]:
# Q5
a = np.random.randint(5,6,10)
a

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5], dtype=int32)

In [9]:
# Q6
a = np.array([1,2,3,4,5,6,7,8,9])
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
# Q7
a = np.random.randint(0,2,9)
a.reshape(3,3)

array([[1, 0, 1],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [15]:
# Q8
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

hori_concat = np.hstack((array1, array2))
vert_concat = np.vstack((array1, array2))

print("Horizontal Concatenation:\n", hori_concat)
print("Vertical Concatenation:\n", vert_concat)

Horizontal Concatenation:
 [[1 2 5 6]
 [3 4 7 8]]
Vertical Concatenation:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [1]:
pip install pandas


   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.5 MB 2.5 MB/s eta 0:00:05
   -- ------------------------------------- 0.8/11.5 MB 1.8 MB/s eta 0:00:06
   -- ------------------------------------- 0.8/11.5 MB 1.8 MB/s eta 0:00:06
   --- ------------------------------------ 1.0/11.5 MB 1.0 MB/s eta 0:00:11
   --- ------------------------------------ 1.0/11.5 MB 1.0 MB/s eta 0:00:11
   ---- ----------------------------------- 1.3/11.5 MB 957.5 kB/s eta 0:00:11
   ------ --------------------------------- 1.8/11.5 MB 1.1 MB/s eta 0:00:09
   ------ --------------------------------- 1.8/11.5 MB 1.1 MB/s eta 0:00:09
   -------- ------------------------------- 2.4/11.5 MB 1.1 MB/s eta 0:00:09
   -------- ------------------------------- 2.4/11.5 MB 1.1 MB/s eta 0:00:09
   ---------- ----------------------------- 2.9/11.5 MB 1.1 MB/s eta 0:00:08
   -------


[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import pandas as pd

In [6]:
df = pd.read_csv("placement.csv")
df.head()



cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1
4  7.52          7.30       1

In [8]:
df.head(2)

cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0

In [12]:
df.tail()

cgpa  resume_score  placed
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

In [13]:
df.describe()

cgpa  resume_score      placed
count  100.0000    100.000000  100.000000
mean     6.9422      6.930500    0.500000
std      1.1192      0.979608    0.502519
min      5.2700      4.950000    0.000000
25%      5.9800      6.190000    0.000000
50%      6.6200      7.055000    0.500000
75%      8.0450      7.640000    1.000000
max      9.4000      9.060000    1.000000

In [14]:
top_left_corner_df = df.iloc[:4 , :3]
top_left_corner_df

cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1

In [18]:
df.loc[1:3 , ['cgpa' , 'placed']]

cgpa  placed
1  6.17       0
2  8.27       1
3  6.88       1

In [19]:
df.loc[1:3 , ['cgpa' , 'placed']]

cgpa  placed
1  6.17       0
2  8.27       1
3  6.88       1

In [20]:
s = df.dtypes

In [22]:
s = df.axes
s

[RangeIndex(start=0, stop=100, step=1),
 Index(['cgpa', 'resume_score', 'placed'], dtype='object')]

In [24]:
s = df.dtypes
s

cgpa            float64
resume_score    float64
placed            int64
dtype: object

In [25]:
b=df.empty
b

False

In [26]:
df.isnull().sum()

cgpa            0
resume_score    0
placed          0
dtype: int64

In [27]:
df.dropna()

cgpa  resume_score  placed
0   8.14          6.52       1
1   6.17          5.17       0
2   8.27          8.86       1
3   6.88          7.27       1
4   7.52          7.30       1
..   ...           ...     ...
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

[100 rows x 3 columns]

In [28]:
i = df.ndim
i

2

In [30]:
df['cgpa'] = df['cgpa'].astype(int)
df

cgpa  resume_score  placed
0      8          6.52       1
1      6          5.17       0
2      8          8.86       1
3      6          7.27       1
4      7          7.30       1
..   ...           ...     ...
95     6          6.38       0
96     8          7.76       1
97     6          7.78       0
98     8          5.63       1
99     6          6.61       0

[100 rows x 3 columns]

In [32]:

df['cgpa'] = df['cgpa'].add(4)
df

cgpa  resume_score  placed
0     12          6.52       1
1     10          5.17       0
2     12          8.86       1
3     10          7.27       1
4     11          7.30       1
..   ...           ...     ...
95    10          6.38       0
96    12          7.76       1
97    10          7.78       0
98    12          5.63       1
99    10          6.61       0

[100 rows x 3 columns]

In [34]:
 df = df.filter(item = ['cgpa' , 'placed'])
df

TypeError: NDFrame.filter() got an unexpected keyword argument 'item'. Did you mean 'items'?

In [35]:
df

cgpa  resume_score  placed
0     12          6.52       1
1     10          5.17       0
2     12          8.86       1
3     10          7.27       1
4     11          7.30       1
..   ...           ...     ...
95    10          6.38       0
96    12          7.76       1
97    10          7.78       0
98    12          5.63       1
99    10          6.61       0

[100 rows x 3 columns]

In [36]:
p=df

In [40]:
p['output']=1
p

cgpa  resume_score  placed  input  output
0     12          6.52       1      1       1
1     10          5.17       0      1       1
2     12          8.86       1      1       1
3     10          7.27       1      1       1
4     11          7.30       1      1       1
..   ...           ...     ...    ...     ...
95    10          6.38       0      1       1
96    12          7.76       1      1       1
97    10          7.78       0      1       1
98    12          5.63       1      1       1
99    10          6.61       0      1       1

[100 rows x 5 columns]

In [41]:
s = df.copy()
s

cgpa  resume_score  placed  input  output
0     12          6.52       1      1       1
1     10          5.17       0      1       1
2     12          8.86       1      1       1
3     10          7.27       1      1       1
4     11          7.30       1      1       1
..   ...           ...     ...    ...     ...
95    10          6.38       0      1       1
96    12          7.76       1      1       1
97    10          7.78       0      1       1
98    12          5.63       1      1       1
99    10          6.61       0      1       1

[100 rows x 5 columns]

In [43]:
p=df.rename(columns={'cgpa':'update_cgpa','resume_score':'semester_marks'})
p

update_cgpa  semester_marks  placed  input  output
0            12            6.52       1      1       1
1            10            5.17       0      1       1
2            12            8.86       1      1       1
3            10            7.27       1      1       1
4            11            7.30       1      1       1
..          ...             ...     ...    ...     ...
95           10            6.38       0      1       1
96           12            7.76       1      1       1
97           10            7.78       0      1       1
98           12            5.63       1      1       1
99           10            6.61       0      1       1

[100 rows x 5 columns]

In [45]:
df.to_csv("student_data.csv")